### ISSUE TITLE
PCRE mutiple balance group can't  work 

### ISSUE THREAD

**Issue by nocanstillbb** [ltrzesniewski/pcre-net#25]
input    : `(1+3 * (4+4) )`
pattern: `^\([^()]+(((?'open'\()[^()]*)+((?'-open'\))[^()]*)+)*(?(open)(?!))\)\s*$`

error infomation  :
```
   at PCRE.Internal.InternalRegex..ctor(String pattern, PcreRegexSettings settings) in /_/src/PCRE.NET/Internal/InternalRegex.cs:line 45
   at PCRE.Internal.Caches.<>c.<.cctor>b__6_0(RegexKey key) in /_/src/PCRE.NET/Internal/Caches.cs:line 9
   at PCRE.Internal.PriorityCache`2.GetOrAdd(TKey key) in /_/src/PCRE.NET/Internal/PriorityCache.cs:line 81
   at PCRE.PcreRegex..ctor(String pattern, PcreRegexSettings settings) in /_/src/PCRE.NET/PcreRegex.cs:line 48
   at PCRE.PcreRegex.Matches(String subject, String pattern) in /_/src/PCRE.NET/PcreRegex.Match.cs:line 236
   at pcre.net.standrad21.Program.Main(String[] args) in C:\Users\hbb\source\repos\pcre.net.standrad21\Program.cs:line 14
```
editPad lite can work well
![image](https://user-images.githubusercontent.com/22405678/118391447-f350a480-b666-11eb-9d82-998448cfbe67.png)

**Comment by ltrzesniewski** [comment]
Your pattern is supported by EditPad, but not by PCRE2, as they don't support the same regex flavor. PCRE2 doesn't handle balancing groups, it provides recursion instead.

You can see it [on regex101](https://regex101.com/r/BXGUg9/1) - `(?'-open'\))` is invalid. See also [the PCRE2 doc](http://www.pcre.org/current/doc/html/pcre2pattern.html#SEC16) about named capturing, and the regular-expressions.info [page about balancing groups](https://www.regular-expressions.info/balancing.html).

If you want to validate math expressions, here's a quick example I put together (don't assume it's correct):

```
(?(DEFINE)
  (?<number> \d+ )
  (?<parens> \( (?&expr) \) )
  (?<atom> \s* [-+]? \s* (?: (?&number) | (?&parens) ) \s* )
  (?<mul> (?&atom) (?: [*/] (?&atom) )* )
  (?<add> (?&mul) (?: [-+] (?&mul) )* )
  (?<expr> (?&add) )
)
^(?&expr)$
```

See it [on regex101](https://regex101.com/r/sOSKPS/2/). Note that it needs `PcreOptions.IgnorePatternWhitespace`.
